import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

test.describe('API: Zarządzanie strukturą danych drzewa', () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeEach(async () => {
    const rootPath = process.cwd();
    const emptyData = path.join(rootPath, 'data', 'empty-data.json');
    const testData = path.join(rootPath, 'data', 'test-data.json');

    if (!fs.existsSync(emptyData)) {
      fs.writeFileSync(emptyData, '[]', 'utf8');
    }
    fs.copyFileSync(emptyData, testData);
  });

  test('POST - create a new person with autogenerated ID', async ({ request }) => {
    const validPayload = {
      imie: 'Adam',
      nazwisko: 'Kowalski',
      plec: 'male',
    };

    const response = await request.post('/api/data', {
      data: validPayload,
    });

    expect(response.status()).toBe(201);

    const body = await response.json();
    expect(body.success).toBe(true);
    expect(body.message).toBe('Zapisano poprawnie');

    expect(body.data).toBeDefined();
    expect(body.data.id).toBe('1');
    expect(body.data.imie).toBe('Adam');
    expect(body.data.nazwisko).toBe('Kowalski');
  });

  test('PUT - update an existing person', async ({ request }) => {
    await request.post('/api/data', {
      data: { imie: 'Jan', nazwisko: 'Test', plec: 'male' },
    });

    const updatedPayload = {
      imie: 'Jan',
      nazwisko: 'Nowak',
      plec: 'male',
    };

    const response = await request.put('/api/data/1', {
      data: updatedPayload,
    });

    expect(response.status()).toBe(200);

    const getResponse = await request.get('/api/data');
    const data = await getResponse.json();

    expect(data.length).toBe(1);
    expect(data[0].nazwisko).toBe('Nowak');
  });

  test('DELETE - remove a person from the tree', async ({ request }) => {
    await request.post('/api/data', {
      data: { imie: 'Jan', nazwisko: 'Test', plec: 'male' },
    });

    const response = await request.delete('/api/data/1');
    expect(response.status()).toBe(200);

    const getResponse = await request.get('/api/data');
    const data = await getResponse.json();
    expect(data.length).toBe(0);
  });

  test('POST - return code error 400 when payload is an array', async ({ request }) => {
    const invalidArrayPayload = [{ imie: 'Jan', nazwisko: 'Kowalski', plec: 'male' }];

    const response = await request.post('/api/data', {
      data: invalidArrayPayload,
    });

    expect(response.status()).toBe(400);

    const body = await response.json();
    expect(body.error).toBe('Bad request');
    expect(body.message).toContain('Przesłane dane muszą być pojedynczym obiektem');
  });

  test('POST - return code error 422 when missing required parameters', async ({ request }) => {
    const missingFieldsPayload = {
      imie: 'ImięBezNazwiskaIPłci',
    };

    const response = await request.post('/api/data', {
      data: missingFieldsPayload,
    });

    expect(response.status()).toBe(422);

    const body = await response.json();
    expect(body.error).toBe('Unprocessable Entity');
    expect(body.message).toContain('Niepoprawny format danych osoby');
  });

  test('POST - reject invalid names starting with lowercase letters', async ({ request }) => {
    const badNamePayload = {
      imie: 'jan',
      nazwisko: 'Kowalski',
      plec: 'male',
    };

    const response = await request.post('/api/data', {
      data: badNamePayload,
    });

    expect(response.status()).toBe(422);
  });

  test('POST - reject invalid date formats', async ({ request }) => {
    const badDatePayload = {
      imie: 'Jan',
      nazwisko: 'Kowalski',
      plec: 'male',
      dataUrodzenia: '2026-07-18',
    };

    const response = await request.post('/api/data', {
      data: badDatePayload,
    });

    expect(response.status()).toBe(422);
  });
});
